### ISSUE TITLE
Descriptions are too verbose

### ISSUE THREAD

**Issue by mafredri** [wmaurer/vscode-change-case#2]
After installing the extension I immediately reacted to the verbose descriptions which imo:

1. Clutter up the menu
2. Are caught by irrelevant keywords

Here's an example of 2.:

![](https://www.dropbox.com/s/6lcwk80aok4mjqt/Screenshot%202015-12-06%2012.45.05.png?dl=1)

And an example for when it actually is in the way, here I want to convert to lower case, but the due to the verbose descriptions the first match is 'dot', and there's a lot of irrelevant matches as well (at least to my expectations, if I want e.g. snake, I search for snake):

![](https://www.dropbox.com/s/5t1ph6f5uo6wkfj/Screenshot%202015-12-06%2012.55.42.png?dl=1)

My suggestion would be to keep the entries in the menu simple, e.g. `Change Case 'lower'`. If a user is interested to see the outcome there is the `Change Case Commands` menu anyway.

**Comment by wmaurer** [comment]
Hi @mafredri, thanks for the suggestion. I do see your point.
I think for some users new to the plugin, the longer descriptions are useful.

My idea right now is to offer a boolean setting which would allow users to turn the long descriptions off.
What do you thjnk?

**Comment by mafredri** [comment]
Personally I think a description for each case in the readme would suffice, but I think an option to turn them either on or off is perfectly fine as well.

**Comment by wmaurer** [comment]
Unfortunately I can't make a setting to turn this on or off, as the titles are hard-coded in a package.json, and not configurable via code :disappointed:

I need to leave the longer descriptions there right now until the VSCode team has had a look at Microsoft/vscode#1147, as I'm struggling to find an example of the fuzzy search not working properly with any other extension apart from mine with the long descriptions :frowning:

**Comment by mafredri** [comment]
Ok, that makes me very sad as the verbosity actually makes it harder for me to use the extension, guess I will uninstall for now but I'll keep an eye out for updates that might make it more bearable :)!

**Comment by mafredri** [comment]
Thanks, love the new release :heart_eyes: !
