### ISSUE TITLE
Consider removing single quotes in the menu

### ISSUE THREAD

**Issue by mafredri** [wmaurer/vscode-change-case#3]
Not exactly an issue with this extension (perhaps more with vscode command matching) but when searching for a command the `'`-quotes can get in the way.

![](https://www.dropbox.com/s/eveen4qso28o280/Screenshot%202015-12-06%2013.01.32.png?dl=1)

On the other hand, when you include the `'` you get the expected result:

![](https://www.dropbox.com/s/hs3kyka7zaxck03/Screenshot%202015-12-06%2013.01.50.png?dl=1)

**Comment by wmaurer** [comment]
Thanks, I'll look into whether change the descripion to *Change Case to camel* solves this problem. I'll also consider raising an issue against VSCode itself.

**Comment by mafredri** [comment]
Cool, thanks! :)

**Comment by wmaurer** [comment]
It's not just that quotes get in the way, *anything* gets in the way. Searching in the command palette seems to only work on exactly what you type, it's not in any sense a fuzzy search. I've raised an issue on the vscode repo: Microsoft/vscode#1147
