### ISSUE TITLE
Should sort all lines when no lines marked

### ISSUE THREAD

**Issue by mms-segu** [wmaurer/vscode-change-case#4]
When I want to sort a file and have not marked anything in it, the default behaviour should be to sort all the lines.
Right now I have to mark everything and then run the sort-command.

**Comment by wmaurer** [comment]
I'm a bit confused about your issue. The vscode-change-case extensions does not provide any sorting functionality at all.

**Comment by mms-segu** [comment]
Wron extension, sorry!
