### ISSUE TITLE
What about kebab-case?

### ISSUE THREAD

**Issue by ValeriiVasin** [wmaurer/vscode-change-case#6]
I know that in the wrapper library it is called [param-case](https://github.com/blakeembrey/change-case/issues/24) which i have no idea from where it is coming, but it was really challenging to find what should I use after installing the extension.

Would be nice to add alias, or at least, add clear description line that shows what is _param_ case. because currently it is not clear. If it is possible for extension..

**Comment by fhelje** [comment]
Kebab casing would be great when you use Riot.js when you jump between component in js and html they have camel casing in js and kebab html

**Comment by wmaurer** [comment]
Thanks for the suggestion.
I've added kebab case as an alias for param case.
