### ISSUE TITLE
Running the contributed command:'extension.changeCase.lower' failed.

### ISSUE THREAD

**Issue by y0n1** [wmaurer/vscode-change-case#7]
Hi,

I received this error, although it did change the fonts to lower case.

**Steps to reproduce:**
1. Fresh install the extension
2. Select all text 
3. Change to lower case as shown in the screenshots.

PS: Good job, great extension, and very useful!

**Comment by wmaurer** [comment]
Sorry, I'm not able to reproduce this error. Are you still getting the error with the latest release of VSCode and change-case?

**Comment by y0n1** [comment]
It seems to be working just fine now
