### ISSUE TITLE
On multi-line strings it duplicate texts

### ISSUE THREAD

**Issue by mcardia** [wmaurer/vscode-change-case#8]
text where cursor is positioned but not selected is duplicated on conversion.
![mcardia_000237](https://cloud.githubusercontent.com/assets/11967511/18918190/6a7369f8-8570-11e6-869b-1d0e224b8364.png)
![mcardia_000238](https://cloud.githubusercontent.com/assets/11967511/18918189/6a6e4202-8570-11e6-9810-af193001b477.png)

**Comment by wmaurer** [comment]
Thanks for the bug report. This has now been fixed.
